[openai]
api_key = "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"
OPENAI_API_KEY = "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"
